.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. konjocoin_qt test_konjocoin_qt
clean: FORCE
	$(MAKE) -C .. konjocoin_qt_clean test_konjocoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_konjocoin_qt_check
konjocoin-qt konjocoin-qt.exe: FORCE
	 $(MAKE) -C .. konjocoin_qt
